remote_theme: mmistakes/minimal-mistakes@4.27.3
title: nky的主页
description: 零零碎碎的记录

plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-include-cache

future: true
paginate: 10
paginate_path: "/page:num/"

show_date: true
read_time: true
search: true

collections:
  pages:
    output: true
    permalink: /:path/

tag_archive:
  type: liquid
  path: /tags/

# jekyll-archives:
#   enabled:
#     - tags
#   layouts:
#     tag: archive-taxonomy
#   permalinks:
#     tag: /tags/:name/


# Analytics
analytics:
  provider               :  "google-gtag"
  google:
    tracking_id          : G-CE82KTLK7T
    anonymize_ip         : true
